"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

NAME = "MeC_BUNO"
APP = ['main.py']
DATA_FILES = []
OPTIONS = {'iconfile': 'MeCBUNO.icns'}

setup(
    app=APP,
    name=NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
